name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule: 
  #   - cron: '0 8 * * *'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Run Yarn Upgrade
        uses: borales/actions-yarn@v4
        with:
          cmd: upgrade # will run `yarn upgrade` command

      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            build
            !build/**/*.md
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build

      - shell: bash
        run: |
          ls -a
      
      # Git Init here, and Force Push to vs-cal-pub repo
      - name: Merge Current Build to Github Page
        run: |
          git clone https://${{ secrets._GITHUB_TOKEN }}@git@github.com:Ysunil016/vs-cal-pub.git
          chmod -R 777 * && chmod -R 777 */*
          cd vs-cal-pub
          cp -r .git ../
          rm -r -f *
          cd ../ 
          cp -r .git ./vs-cal-pub
          cp -r ./build/* ./vs-cal-pub
          cd vs-cal-pub
          date >> revision.txt 
          ls -a

      - name: Push Repo to Github Page
        run: |
          cd vs-cal-pub
          git config --global user.email "atworksunil@gmail.com"
          git config --global user.name "Yadav, Sunil"

          git add .
          git commit -m "${GITHUB_SHA}"
          git push -u origin main --force
