name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule: 
  #   - cron: '0 8 * * *'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Run Yarn Upgrade
        uses: borales/actions-yarn@v4
        with:
          cmd: upgrade # will run `yarn upgrade` command

      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            build
            !build/**/*.md
          retention-days: 1

  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download build artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-artifact
  #         path: build

  #     - shell: bash
  #       run: |
  #         ls -a
      
  #     # Git Init here, and Force Push to ysunil016.github.io repo
  #     - name: Merge Current Build to Github Page
  #       run: |
  #         git clone https://${{ secrets._GITHUB_TOKEN }}@github.com/Ysunil016/ysunil016.github.io.git
  #         chmod -R 777 * && chmod -R 777 */*
  #         cd ysunil016.github.io
  #         cp -r .git ../
  #         rm -r -f *
  #         cd ../ 
  #         cp -r .git ./ysunil016.github.io
  #         cp -r ./build/* ./ysunil016.github.io
  #         cd ysunil016.github.io
  #         date >> revision.txt 
  #         ls -a

  #     - name: Push Repo to Github Page
  #       run: |
  #         cd ysunil016.github.io
  #         git config --global user.email "atworksunil@gmail.com"
  #         git config --global user.name "Yadav, Sunil"

  #         git add .
  #         git commit -m "${GITHUB_SHA}"
  #         git push -u origin main --force

# git init
# git add README.md
# git commit -m "first commit"
# git branch -M main
# git remote add origin https://github.com/Ysunil016/ysunil016.github.io.git
# git push -u origin main
