name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule: 
  #   - cron: '0 8 * * *'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Run Yarn Upgrade
        uses: borales/actions-yarn@v4
        with:
          cmd: upgrade # will run `yarn upgrade` command

      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command

      # - name: Merge Current Build to Github Page
      #   run: |
      #     chmod -R 777 * && chmod -R 777 */*
      #     rm -r -f ./docs/*
      #     cp -r ./build/* ./docs
  
      #     git config --global user.email "atworksunil@gmail.com"
      #     git config --global user.name "Yadav, Sunil"

      #     git add .
      #     git commit -m "${GITHUB_SHA}"
      #     git push -u origin main --force